var osenv = require('osenv');
var colors = require('colors');
var aws4  = require('aws4');
var AWS = require('aws-sdk');
var request = require('request');
var fs = require('fs');
var mkdirp = require('mkdirp');

var home = osenv.home();
var credentialsFile = home + '/.hocus/credentials.json';

var actions = {};

actions.deleteModel = function(modelName){
	var credentials = JSON.parse(fs.readFileSync(credentialsFile)).default;
	
	AWS.config.update({
		accessKeyId: credentials.awsAccessKey,
		secretAccessKey : credentials.awsSecretAccessKey,
		region : credentials.regionName
	});

	var params = {
		TableName : modelName		
	};
	
	var dynamodb = new AWS.DynamoDB();
	dynamodb.deleteTable( params, function( err, data ){
		if ( err ) throw err;
		
		fs.unlinkSync('./config/models/' + modelName + '.json');
		
		fs.unlinkSync('./models/'+ modelName + '.json');

		console.log('    deleted model: '.green + modelName.green );
	});
}

actions.generateModel = function(modelName,attributes){
	var credentials = JSON.parse(fs.readFileSync(credentialsFile)).default;
	
	AWS.config.update({
		accessKeyId: credentials.awsAccessKey,
		secretAccessKey : credentials.awsSecretAccessKey,
		region : credentials.regionName
	});
	
	var params = {
		TableName : modelName,
		AttributeDefinitions : [
			{ 
				AttributeName : 'hocus_id',
				AttributeType : 'S'
			}
		],
		KeySchema : [
			{
				AttributeName : 'hocus_id',
				KeyType : 'HASH'
			}
		],
		ProvisionedThroughput: {
			ReadCapacityUnits: 5,
			WriteCapacityUnits: 5
		}
	};
	
	var dynamodb = new AWS.DynamoDB();
	dynamodb.createTable( params, function( err, data ){
		if ( err ) throw err;

		/* Store the AWS config for the DynamoDB table in config/models/{modelName}.json */
		var model = {
			tableName : data.TableDescription.TableName,
			tableARN : data.TableDescription.TableArn,
			tableCreated : data.TableDescription.CreationDateTime,
			tableCapacity : {
				readUnits : data.TableDescription.ProvisionedThroughput.ReadCapacityUnits,
				writeUnits : data.TableDescription.ProvisionedThroughput.WriteCapacityUnits,
			}
		}
		mkdirp('./config/models');
		fs.writeFileSync('./config/models/' + modelName + '.json', JSON.stringify(model, null, 4));

		/* Store the json schema for the model in models/{modelName}.json */
		var schema = {
			"title" : modelName + ' schema',
			"type" : "object",
			"properties" : {
				"hocus_id" : {
					"description" : "A UUID generated by hocus. Don't delete it.",
					"type" : "string"
				}
			},
			"required" : []
		};

		if ( typeof attributes !== 'undefined' ){
			attributes.forEach( function( attribute ){
				if ( attribute.indexOf(':') > -1 ){
					var pieces = attribute.split(':');
					schema.properties[ pieces[0] ] = {
						"type" : pieces[1]
					}
				} else {
					schema.properties[ attribute ] = {
						"type" : "string"
					}
				}
			});
		}
		fs.writeFileSync('./models/'+ modelName + '.json', JSON.stringify(schema, null, 4));


		console.log('    created new model: '.green + modelName.green );
	});

};

actions.configure = function(data){	
     
	mkdirp.sync(home + '/.hocus');

	
	var credentials = {};
    
    if (fs.existsSync(credentialsFile)){
    	credentials = JSON.parse(fs.readFileSync(credentialsFile));
    }
    var profile = data.profile;
    delete data.profile;

    credentials[ profile ] = data;

	fs.writeFileSync(home + '/.hocus/credentials.json', JSON.stringify(credentials, null, 4));
	console.log('Hocus configuration complete.'.green);
    
};

actions.new = function(appName){
	var home = osenv.home();
    var credentialsFile = home + '/.hocus/credentials.json';
    if (fs.existsSync(credentialsFile)){
		var credentials = JSON.parse(fs.readFileSync(credentialsFile)).default; 

		/* Create a new API on AWS API Gateway */
		var opts = {
			host: 'apigateway.us-east-1.amazonaws.com', 
			path: '/restapis',
			body : JSON.stringify({
				name : appName
			})
		};

		aws4.sign(opts, {
			accessKeyId: credentials.awsAccessKey, 
			secretAccessKey: credentials.awsSecretAccessKey
		});

		request.post('https://apigateway.us-east-1.amazonaws.com/restapis', opts, function (err, resp, body){
			if (err) throw err;

			var data = JSON.parse(body);

			if (resp.statusCode > 399){
				console.log(resp.statusCode);
				if (resp.statusCode === 403){
					console.log('Your credentials do not have access to create a new API in the AWS API Gateway.'.red);
				} else {
					console.log('An error occured creating a new AWS API Gateway.');
				}
				console.log('AWS Response was: ');
				console.log(data);
				console.log('');
				console.log('Hocus app not created.'.red)
			} else {          

				var appConfig = {
					name : data.name,
					id : data.id,
					createdDate: data.createdDate
				};

				console.log('   created new API in AWS API Gateway with ID: '.green + appConfig.id);          

				/* Create folder structure for the app */
				var rootDir = (typeof appName === 'undefined') ? '.' : appName;

				mkdirp.sync(rootDir + '/models');
				console.log('   created models'.green);

				mkdirp.sync(rootDir + '/views');
				console.log('   created views'.green);

				mkdirp.sync(rootDir + '/controllers');
				console.log('   created controllers'.green);

				mkdirp.sync(rootDir + '/static');
				console.log('   created static'.green);

				mkdirp.sync(rootDir + '/config');

				console.log('   created config'.green);
				mkdirp.sync(rootDir + '/.hocus');

				fs.writeFileSync(rootDir +'/.hocus/appConfig.json', JSON.stringify(appConfig, null, 4));
				console.log('   created /.hocus/appconfig.json'.green);

				console.log('Hocus app created.'.green);
			}
		});      
	} else {
		console.log('You need to run ' + 'hocus configure'.blue + ' before you can do this.');
	}
};

module.exports = actions;